version: "3.9"

services:
  app:
    build: .
    ports:
      - 8080:25000
    environment:
      - DB_USER=db_user
      - DB_PASSWORD=db_password
      - DB_NAME=db_name
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
